```{r pitchers}

library(quanteda)
library(tidyverse)

#Read in data, cast as tibble
pitchers <-  read_csv("stats.csv")
pitchers <- tibble(pitchers)

pitchers <- pitchers %>% mutate(name=paste(first_name, last_name))

pitchers <- pitchers[order(pitchers$player_age),]

pitchers <- pitchers[order(pitchers$name),]



#Aggregate by age and find the mean OBP for each age
pitchers_aggregated_by_age <- pitchers %>%                                       
  group_by(player_age) %>%                        
  summarise_at(vars(on_base_percent),          
               list(OBP = mean))               

#The original idea was to graph the pitcher data by age, but we ran into a problem. Obviously if your OBP jumps too much, you get booted. So the average was relatively stable over time, except on the old end. 
ggplot(pitchers_aggregated_by_age, aes(player_age, OBP, fill = "green")) +
  geom_bar(stat = "identity", show.legend = FALSE) + 
  ggtitle("OBP by age") +
  theme(plot.title = element_text(hjust = 0.5))


#The remedy is to find the average OBP by "year in the league".

#Add an empty column that we can populate in the next chunk
emptycolumn <- c("Years_In_Pitching")
pitchers[ , emptycolumn] <- NA


pitchers$Years_In_Pitching[1]<-1

i<-2
while (i < length(pitchers$Years_In_Pitching)){
  if(i==1){
    pitchers$Years_In_Pitching[i]=1
    i=i+1
    }
  else if(pitchers$name[i]==pitchers$name[i-1]){
    pitchers$Years_In_Pitching[i]=pitchers$Years_In_Pitching[i-1]+1
    i=i+1
    }
  else if(pitchers$name[i]!=pitchers$name[i-1]){
    pitchers$Years_In_Pitching[i] = 1
    i=i+1
  }
}

#Aggregate by Years In Pitching and find the mean OBP for each of these
pitchers_by_years_pitched <- pitchers %>%                                       
  group_by(Years_In_Pitching) %>%                        
  summarise_at(vars(on_base_percent),          
               list(OBP = mean))       

ggplot(pitchers_by_years_pitched, aes(Years_In_Pitching, OBP, fill = "green")) +
  geom_bar(stat = "identity", show.legend = FALSE) + 
  ggtitle("OBP by Years in Pitching") +
  theme(plot.title = element_text(hjust = 0.5))

```
```{r}
#Look at the trajectories of several careers.

AndyBenes <- pitchers %>% filter(name == "Andy Benes")

ggplot(AndyBenes, aes(Years_In_Pitching, on_base_percent, fill = "green")) +
  geom_bar(stat = "identity", show.legend = FALSE) + 
  ggtitle("OBP by Years in Pitching") +
  theme(plot.title = element_text(hjust = 0.5))

AJBurnett <- pitchers %>% filter(name == "A.J. Burnett")

ggplot(AJBurnett, aes(Years_In_Pitching, on_base_percent, fill = "green")) +
  geom_bar(stat = "identity", show.legend = FALSE) + 
  ggtitle("OBP by Years in Pitching") +
  theme(plot.title = element_text(hjust = 0.5))

AdamWainwright <- pitchers %>% filter(name== "Adam Wainwright")

ggplot(AdamWainwright, aes(Years_In_Pitching, on_base_percent, fill = "green")) +
  geom_bar(stat = "identity", show.legend = FALSE) + 
  ggtitle("OBP by Years in Pitching") +
  theme(plot.title = element_text(hjust = 0.5))

AndyPettitte <- pitchers %>% filter(name== "Andy Pettitte")

ggplot(AndyPettitte, aes(Years_In_Pitching, on_base_percent, fill = "green")) +
  geom_bar(stat = "identity", show.legend = FALSE) + 
  ggtitle("OBP by Years in Pitching") +
  theme(plot.title = element_text(hjust = 0.5))


```


```{r curious}

#Curious about the effect of age AND years in pitching on OBP

mylm <- lm(on_base_percent ~ player_age * Years_In_Pitching, data = pitchers)

#Analyze Findings
summary(mylm)
summary(mylm)$r.squared 





```


```{r prepare data for interactive graph}

pitchers <-  read_csv("stats.csv")
pitchers <- tibble(pitchers)

pitchers <- pitchers %>% mutate(name=paste(first_name, last_name))

pitchers <- pitchers[order(pitchers$player_age),]

pitchers <- pitchers[order(pitchers$name),]

pitchers <- pitchers %>% mutate(decade = (year %/% 10)*10)



pitchers


```














```{r interactive graph }


#devtools::install_github("bokeh/rbokeh@v0.6.3")

library(rbokeh)
library(quanteda)
library(tidyverse)

#Read in data, cast as tibble
pitchers <-  read_csv("stats.csv")
pitchers <- tibble(pitchers)

pitchers <- pitchers %>% mutate(name=paste(first_name, last_name))

pitchers <- pitchers %>% mutate(name=paste(first_name, last_name))

pitchers <- pitchers[order(pitchers$player_age),]

pitchers <- pitchers[order(pitchers$name),]


#Add an empty column that we can populate in the next chunk
emptycolumn <- c("Years_In_Pitching")
pitchers[ , emptycolumn] <- NA


pitchers$Years_In_Pitching[1]<-1

i<-2
while (i < length(pitchers$Years_In_Pitching)){
  if(i==1){
    pitchers$Years_In_Pitching[i]=1
    i=i+1
    }
  else if(pitchers$name[i]==pitchers$name[i-1]){
    pitchers$Years_In_Pitching[i]=pitchers$Years_In_Pitching[i-1]+1
    i=i+1
    }
  else if(pitchers$name[i]!=pitchers$name[i-1]){
    pitchers$Years_In_Pitching[i] = 1
    i=i+1
  }
}

pitchers <- pitchers %>% mutate(decade = (year %/% 10)*10)

pitchers

figure() %>%
  ly_points(x = on_base_percent, y = p_strikeout, color = Years_In_Pitching,
  data = pitchers, hover = list(name, year, on_base_percent, p_strikeout))




library(ggplot2)
library(plotly) 
p <- ggplot(pitchers, aes(on_base_percent, p_strikeout, colour=decade)) + geom_point()
 ggplotly(p)









```






