To an outside person who wouldn't know the tiny details about baseball, one might think that pitcher success is strictly based off of wins. Let's explore what kinds of things would factor into projecting wins in a season. 
```{r Non-Sports Background}
library(ggplot2)
#Read in data
advancedPitchers <-  read_csv("AdvancedPitcherMetrics.csv")
advancedPitchers <- tibble(advancedPitchers)
advancedPitchers <- advancedPitchers %>% mutate(name=paste(first_name, last_name))

advancedPitchers <- advancedPitchers %>% mutate(name=paste(first_name, last_name))

advancedPitchers <- advancedPitchers[order(advancedPitchers$name),]

#Need to take out 2020 for projecting wins
```


```{r Advanced Graphs}

library(ggplot2)

ggplot(data = advancedPitchers) + geom_point(aes(x = fastball_avg_speed, y = p_win, color= year))

ggplot(data = advancedPitchers) + geom_point(aes(x = breaking_avg_speed, y = p_win, color= year))

ggplot(data = advancedPitchers) + geom_point(aes(x = offspeed_avg_speed, y = p_win, color= year))

ggplot(data = advancedPitchers) + geom_point(aes(x = fastball_avg_spin, y = p_win, color= year))

ggplot(data = advancedPitchers) + geom_point(aes(x = offspeed_avg_spin, y = p_win, color= year))

ggplot(data = advancedPitchers) + geom_point(aes(x = breaking_avg_spin, y = p_win, color= year))

ggplot(data = advancedPitchers) + geom_point(aes(x = hard_hit_percent, y = p_win, color= year))

ggplot(data = advancedPitchers) + geom_point(aes(x = exit_velocity_avg, y = p_win, color= year))

ggplot(data = advancedPitchers) + geom_point(aes(x = launch_angle_avg, y = p_win, color= year))

ggplot(data = advancedPitchers) + geom_point(aes(x = barrel_batted_rate, y = p_win, color= year))

ggplot(data = advancedPitchers) + geom_point(aes(x = sweet_spot_percent, y = p_win, color= year))

ggplot(data = advancedPitchers) + geom_point(aes(x = solidcontact_percent, y = p_win, color= year))

ggplot(data = advancedPitchers) + geom_point(aes(x = year, y = p_win, color= year))

```
